FROM mcr.microsoft.com/devcontainers/typescript-node:1-22

WORKDIR /app

# keep the container running
CMD ["sleep", "infinity"]
# CMD ["npm", "install"]

# RUN pwd
# RUN ls
# RUN npm install
# RUN npm run start
# Start the Angular app (use --host to allow access from outside the container)
# CMD ["npm", "start", "--", "--host", "0.0.0.0"]
# CMD ["DEBUG=pure-dash:*", "npm", "restart"]